### PR TITLE
Hopefully i added a splash to recc :)

### PR DESCRIPTION
**Pull request by Khhs167**
Wrong branch tho... welp...

### CODE REVIEW

**Comment by RedCubeDev-ByteSpace** [comment]
alright looks good so far
by splash you mean the crash popup right?
also wdym wrong branch lol
i mean your version seems to be a few commits behind but thats not really a problem lol

**Comment by Khhs167** [comment]
1. Splash = crash popup
2. i commited to extented-highlighting(...)

**Comment by RedCubeDev-ByteSpace** [comment]
i see i see alrighty
all looks good to me ^^

**Comment by scoobydoofacethingdie** [comment]
water gets splashed to your mouth

**Pull request merged**
