### PR TITLE
make console text white after saying build error

### PR DESCRIPTION
**Pull request by scoobydoofacethingdie**
dont you hate it when your input text becomes red

### CODE REVIEW

**Comment by tokorv** [comment]
Can't wait for ReCT to blow up and someone complains the text turns white on their white terminal theme after a build error.
JK no one would ever use a white terminal theme... I hope.

**Comment by scoobydoofacethingdie** [comment]
> Can't wait for ReCT to blow up and someone complains the text turns white on their white terminal theme after a build error.
> JK no one would ever use a white terminal theme... I hope.

come on

**Comment by tokorv** [comment]
> > Can't wait for ReCT to blow up and someone complains the text turns white on their white terminal theme after a build error.
> > JK no one would ever use a white terminal theme... I hope.
> 
> come on

I'm sorry 😤 I wish you luck on your pull request journey

**Review by tokorv — COMMENTED** [review]
looks good chief

**Comment by RedCubeDev-ByteSpace** [comment]
looks good to me

**Pull request merged**
