### PR TITLE
Improved rctc

### PR DESCRIPTION
**Pull request by Khhs167**
I hope this code works out... It basically adds rpm support(and the filetype rcp2)

Commands
rctc add [package] - adds a package to the current dir
rctc remove [package] - removes a package from the current dir
rctc create -v2 - makes a package compatible project(.rcp2)

Hopefully everything works out :)

### CODE REVIEW

**Comment by Khhs167** [comment]
Any files can be the newer verisons(not mine) except rctc, cos idk if i did anything to them(nothing important afaik)

**Comment by scoobydoofacethingdie** [comment]
those changes sound pretty good

**Comment by RedCubeDev-ByteSpace** [comment]
hey sooo uhm ReCT packages work globally meaning every project accesses the same Packages.
What does the rcp2 file do?

**Comment by Khhs167** [comment]
> hey sooo uhm ReCT packages work globally meaning every project accesses the same Packages.
> What does the rcp2 file do?

It auto installs packages, also, i wonder if it is a good idea to then uninstall them?

**Comment by RedCubeDev-ByteSpace** [comment]
am a little conflicted on this one
i think its really cool that you put in the effort of making this
but on the other hand im not sure if i like the way its implemented...
i think ill be closing this pullrequest and will be implementing your code in a bit of a different way, is that alright?

**Comment by Khhs167** [comment]
Ight

**Pull request closed without merging**
